# PODSTAWOWE INFORMACJE
name: budzetownik
description: "Aplikacja do projektowania budzetu domowego"
publish_to: 'none'
version: 1.0.0+1

# WERSJA
environment:
  sdk: ">=3.10.0 <4.0.0"

# POTRZEBNE W DZIAŁAJĄCEJ APLIKACJI
dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1

# POTRZEBNE PODCZAS TWORZENIA
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg